# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |group|

    Name = "downloader"

    group.vm.define Name do |instance|
      instance.vm.box = "ubuntu/focal64"
      instance.vm.hostname = Name
      instance.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
      instance.vm.provision "shell", path: "download.sh", args: "/home/vagrant"
      instance.vm.provider :virtualbox do |vb|
        vb.name = Name
        vb.cpus = 1
        vb.memory = 1024
      end
    end
   
  end
