# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  Name = "i-k8s-ubuntu"

  #=============#
  # Online Node #
  #=============#

    config.vm.define Name do |cfg|
      # Vagrant box Info
      cfg.vm.box = "generic/ubuntu2004"
      cfg.vm.host_name = Name
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 

      # VirtualBox system resource config
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = Name
        vb.cpus = 2
        vb.memory = 3072
      end

      # Network settings
      #   SSH connection
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"

      # Move files
      cfg.vm.provision "file", source: "./setup", destination: "$HOME/setup"

      # Make executable
      cfg.vm.provision "shell", inline: "chmod 711 /home/vagrant/setup/*.sh"
      cfg.vm.provision "shell", inline: "sed -i -e 's/\r$//' /home/vagrant/setup/*.sh"
    end

end
