# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |group|

    Name = "downloader"

    group.vm.define Name do |instance|
      instance.vm.box = "ubuntu/focal64"
      instance.vm.hostname = Name
      instance.vm.provision "shell", path: "online-downloader.sh"
      instance.vm.provider :virtualbox do |vb|
        vb.name = Name
        vb.cpus = 1
        vb.memory = 1024
      end
    end
   
  end
