# Metadata, config, version information for Kubernetes cluster
node:
  master:
    count: 3
    ip_base: 192.168.1.10
    hname_base: k8s-m
  worker:
    count: 1
    ip_base: 192.168.1.20
    hname_base: k8s-w
  nic: enp0s3
docker:
  versions:
    ce: 5:20.10.14~3-0~ubuntu-focal
    cli: 5:20.10.14~3-0~ubuntu-focal
    containerd: 1.5.11-1
  registry:
    ip: 192.168.2.10
    port: 8443
kubernetes:
  versions:
    controlplane: v1.23.5
    kubectl: 1.23.5-00
    kubelet: 1.23.5-00
    kubeadm: 1.23.5-00
    kube_apiserver: v1.23.5
    kube_controller_manager: v1.23.5
    kube_scheduler: v1.23.5
    kube_proxy: v1.23.5
    pause: 3.6
    etcd: 3.5.1-0
    coredns: v1.8.6
  const:
    cidr: 172.16.0.0/16
    apiserver_port: 6443
cni:
  yaml: https://projectcalico.docs.tigera.io/manifests/calico.yaml
haproxy:
  version:
    short: 2.5
    long: 2.5.6-1ppa1~focal
  fe_port: 26443
keepalived:
  version: "1:2.0.19-2ubuntu0.2"
  vip: 192.168.1.10
