# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  Name = "i2-k8s"

  #=============#
  # Online Node #
  #=============#

    config.vm.define Name do |cfg|
      # Vagrant box Info
      cfg.vm.box = "centos/7"
      cfg.vm.host_name = Name
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 

      # VirtualBox system resource config
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = Name
        vb.cpus = 2
        vb.memory = 3072
      end

      # Network settings
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh" # SSH connection

      # Execute shell commands
      # cfg.vm.provision "shell", path: "config.sh"
      cfg.vm.provision "shell", path: "install_pkg.sh"
      # cfg.vm.provision "shell", path: "master_node.sh"
    end

end
