Vagrant.configure("2") do |config|

    config.vm.define "downloader" do |server|
      server.vm.box = "ubuntu/focal64"
      server.vm.hostname = "downloader"
      server.vm.provision "shell", path: "downloader.online.sh"
      server.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--memory', '2048']
      end
    end

  end
