# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  Name = "docker-prac"

  #=============#
  # Online Node #
  #=============#

    config.vm.define Name do |cfg|
      # Vagrant box Info
      cfg.vm.box = "centos/7"
      cfg.vm.host_name = Name
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 

      # VirtualBox system resource config
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = Name
        vb.cpus = 2
        vb.memory = 3072
      end

      # Network settings
      #   SSH connection
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"

      cfg.vm.provision "shell", path: "./setup.sh"
    end

end
