# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  Masters = 3 # number of master nodes
  Workers = 1 # number of worker nodes
  #Ver = '1.18.4' # Kubernetes Version to install

  #==============#
  # Master Nodes #
  #==============#

  (1..Masters).each do |i|
    vm = "k8s-m#{i}"
    config.vm.define vm do |cfg|
      # Vagrant box info
      cfg.vm.box = "ubuntu/focal64"
      cfg.vm.host_name = vm
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true

      # VirtualBox system resource config
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "#{vm}(github_haeramkeem)"
        vb.cpus = 2
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/k8s-HA"]
      end

      # Network settings
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}" # NAT private network: 192.168.1.101~3
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh" # SSH connection

      # Execute shell commands
      cfg.vm.provision "shell", path: "global_config.sh", args: [Masters, Workers]
      cfg.vm.provision "shell", path: "k8s_precondition.sh"
      cfg.vm.provision "shell", path: "install_docker_k8s.sh"

      # Move files
      cfg.vm.provision "file", source: "./master_node.sh", destination: "$HOME/setup.sh"

      # Make executable
      cfg.vm.provision "shell", inline: "chmod 711 /home/vagrant/*.sh"
      cfg.vm.provision "shell", inline: "sed -i -e 's/\r$//' /home/vagrant/setup.sh"
    end
  end

  #==============#
  # Worker Nodes #
  #==============#

  (1..Workers).each do |i|
    vm = "k8s-w#{i}"
    config.vm.define vm do |cfg|
      # Vagrant box info
      cfg.vm.box = "ubuntu/focal64"
      cfg.vm.host_name = vm
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true

      # VirtualBox system resource config
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "#{vm}(github_haeramkeem)"
        vb.cpus = 1
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/k8s-HA"]
      end

      # Network settings
      cfg.vm.network "private_network", ip: "192.168.1.20#{i}" # NAT private network: 192.168.1.201~3
      cfg.vm.network "forwarded_port", guest: 22, host: "6020#{i}", auto_correct: true, id: "ssh" # SSH connection

      # Execute shell commands
      cfg.vm.provision "shell", path: "global_config.sh", args: [Masters, Workers]
      cfg.vm.provision "shell", path: "k8s_precondition.sh"
      cfg.vm.provision "shell", path: "install_docker_k8s.sh"

      # Move files
      cfg.vm.provision "file", source: "./worker_node.sh", destination: "$HOME/setup.sh"

      # Make executable
      cfg.vm.provision "shell", inline: "chmod 711 /home/vagrant/*.sh"
      cfg.vm.provision "shell", inline: "sed -i -e 's/\r$//' /home/vagrant/setup.sh"
    end
  end

end
